SELECT
    id,
    game_name,
    published_year,
    min_players_intervals,
    max_players_intervals,
    game_duration_intervals,
    categories,
    mechanics,
    family,
    designer,
    artist,
    publisher,
    SUM(nb_of_ratings) as nb_of_ratings,
    avg(avg_rating) as avg_rating,
    avg(bayes_avg) as bayes_avg,
    SUM(owned) as owned,
    SUM(people_wishing) as people_wishing,
    SUM(nb_weights) as nb_weights,
    avg(avg_difficulty) as avg_difficulty,
    bgg_rank,
    difficulty,
    AVG(engagement_rate) as engagement_rate,
    type,
    -- avg(price) as price,
    -- avg(price_over_quality) as price_over_quality,
    -- avg(estimated_turnover) as estimated_turnover,
    AVG(mean_vader) as mean_vader
FROM {{ ref('master_bgg_features_count_enriched') }} as price
GROUP BY id,
    game_name,
    published_year,
    min_players_intervals,
    max_players_intervals,
    game_duration_intervals,
    categories,
    mechanics,
    family,
    designer,
    artist,
    publisher,
    bgg_rank,
    difficulty,
    type