version: 2

sources:
  - name: bgg_dataset_1
    tables:
<<<<<<< HEAD
      - name: BGG_Data_set
        identifier: BGG
      - name: bgg_price_merged
        identifier: price
  - name: bgg_dataset_2
    tables:
      - name: bgg-26m-review
        identifier: reviews
      - name: games_detailed_info2025
        identifier: detailed
  - name: bgg_store_top_sales
    tables:
      - name: bgg-clean
        identifier: top-sales
  - name: dataset_sales_clean
    tables:
      - name: data_sales_clean
        identifier: sales
=======
      - name: BGG_Data_Set
      - name: bgg_price_merged
  - name: bgg_dataset_3
    tables:
      - name: bgg_categories
      - name: bgg_mechanics
      - name: bgg_themes
>>>>>>> 7f6527120f4ff510561f15c0c19cc30132c9b3b7
